### ISSUE TITLE
Version 1.4.0 not working correctly

### ISSUE THREAD

**Issue by paul-keller** [froemken/repair_translation#10] opened 2018-05-07 13:06 UTC
I have got a TYPO3 8.7.13 running with three languages. After updating repair_translation from version 1.2.2 to 1.4.0 all filelinks to files in the translated language were not displayed anymore. Only if the file was the same in all languages, the title of the file was displayed in the correct language.
But if a content element had links to different files in every language, these link were not displayed in the other languages any more.
Downgrading to 1.2.2 solved the problem.

**Comment by froemken** [comment] 2018-05-08 05:45
Please tell me the used extension, tablename and column. If it is a private extension I need the TCA of this column. Further I need the language settings from TypoScript: sys_language_mode and so on.

In TYPO3 8 the l10n_mode has been removed. If you need something similar you have to use this one:
https://docs.typo3.org/typo3cms/TCAReference/8.7/singlehtml/Index.html#localizechildrenatparentlocalization

Nice greetings

Stefan

**Comment by MichelGeorgy** [comment] 2018-05-30 09:34
I guess the problem is that your field is missing the configuration allowLanguageSynchronization in TCA which was introduced in https://forge.typo3.org/issues/79658. 

If this configuration is missing the field has no setting in the json and repair_translation then assumes that you want to use the default / parent record. See function 'configuredToUseDefaultLanguage'  in https://github.com/froemken/repair_translation/blob/master/Classes/SignalSlot/Repair.php

**Comment by W4ldgeist** [comment] 2018-06-13 14:41
I can confirm that 1.4 broke the translation on a 8.7.11 in a custom extension. The TCA is identical to that of textmedia column media. I rolled back to 1.2.2. and it works again.

**Comment by froemken** [comment] 2018-07-03 14:23
Did someone of you have an extension where I can test that?

**Comment by j-lang** [comment] 2018-07-23 09:31
The same issue with Typo3 7.6.30 and news 6.3.0 after update to 1.4.0. non translated images and relations are not shown. After downgrade to 1.2.2 output is correct again.

**Comment by astehlik** [comment] 2018-08-20 13:32
The problem seems to be connected to the mergeIfNotBlank setting.

When I disable the setting everything works fine with version 1.4.

My test case is the fal_related_files field in the news extension (version 3.2.9).

**Comment by herzogkienast** [comment] 2018-09-10 12:28
In TYPO3 7.6.31 everything works fine with tx_news and repair_translation 1.4.0 - please note - you need to localize the attached files in tx_news. Perhaps you can solve your problems in your language settings in setup for language config. So please post you TS to take a look.
BTW - Thank you Stefan für this realy helpful extension.

**Comment by eBornstein** [comment] 2019-01-15 10:12
Sry, but repair_translation 1.4.0 works ONLY if you localize the news. If news are configured with "all language" the images are not shown in translation. I rolled back to 1.2.2. and it works again.

**Comment by webdev2027** [comment] 2019-02-04 09:15
Same here ... I've written an own extension with the FAL images. `1.4.0` isn't working. Now I use your great extension in version `1.2.2` and it works properly. I thought, `TYPO3 8.7` can handle this from core, but they don't. ... really a pity.

**Comment by froemken** [comment] 2019-05-16 21:37
Hello all together,

I have just uploaded version 1.4.1 to Git. Please test that version. If it works for you I will push it to TER

Stefan

**Comment by froemken** [comment] 2019-05-16 21:38
Thank you @astehlik 
Good hint to start my search

@j-lang 
Thank you for the exact versions which helped a lot.

**Comment by kitzberger** [comment] 2019-07-09 21:57
@froemken, i can confirm that 1.4.1 does work for my extbase extension with TYPO3 8.7 LTS. Cheers, Philipp

**Comment by froemken** [comment] 2019-07-10 12:57
As it works now, I can close this issue now and tag it for composer.
Thank you for your hints and support

Stefan

**Closed as completed by froemken** 2019-07-10 12:57 UTC
